[tool.poetry]
name = "boardgamerag"
version = "0.1.0"
description = ""
authors = ["Eric Fan <yikai5518@gmail.com>"]
readme = "README.md"
packages = [{include = "chatbot", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
langchain = "^0.3.5"
langgraph = "^0.2.40"
langchain-openai = "^0.2.4"
streamlit = "^1.39.0"
pydantic = "^2.9.2"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
mypy = "^1.11.2"
ruff = "^0.6.3"
pre-commit = "^3.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
# By default, Ruff enables Flake8's E and F rules
# Pyflakes - F, pycodestyle - E, W
# flake8-builtins - A
# Pylint - PLC, PLE, PLW
# isort - I
lint.select = ['E', 'F', 'W', 'A', 'PLC', 'PLE', 'PLW', 'I']
